In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("stock_data.csv")

In [4]:
df

          Date    Open    High     Low   Close    Volume
0   2026-01-02  101.09  103.37  100.08  102.04   89377.0
1   2026-01-05  101.05  101.99   99.91  100.58   88404.0
2   2026-01-06  102.41  103.15   99.47  101.36   94045.0
3   2026-01-07  105.35  108.05  103.53  106.87   72352.0
4   2026-01-08  105.13  109.88  104.24  107.49   79790.0
5   2026-01-09  104.91  108.22  103.42  107.07   81919.0
6   2026-01-12  107.95  109.49  104.84  106.57   45600.0
7   2026-01-13  109.53  111.44  107.88     NaN   69124.0
8   2026-01-14  108.89  111.08  107.60  109.85   67643.0
9   2026-01-15  110.07  114.76  109.21  112.32   80764.0
10  2026-01-16  109.43  111.85  108.13  108.77   49007.0
11  2026-01-19  108.79  109.79  106.87  108.72  450000.0
12  2026-01-20  109.43  110.92  105.67  107.52   96835.0
13  2026-01-21  106.18  107.28  102.64  104.09   77410.0
14  2026-01-22  103.28  106.28  102.27  105.21   84080.0
15  2026-01-23  102.47  106.05  101.45  105.48   80447.0
16  2026-01-26  100.84  102.72   99.25  101.00   48208.0
17  2026-01-27  101.61  105.43   99.76  103.92   96491.0
18  2026-01-28  100.18  101.80   98.35  101.20       NaN
19  2026-01-29   97.83   98.89   95.17   96.84   58589.0
20  2026-01-09  104.91  108.22  103.42  107.07   81919.0
21  2026-02-02  100.47  104.83   99.84  103.85   57453.0
22  2026-02-03  100.79  101.81  100.05  101.02   76212.0
23  2026-02-04   98.42  103.33   96.57  101.85   83525.0
24  2026-02-05   97.64  100.11   91.29   92.70   87202.0
25  2026-02-06   98.04  100.96   97.53   99.98   72635.0
26  2026-02-09   96.17   98.48   95.52   96.64   73828.0
27  2026-02-10   97.05   99.07   95.25   96.75  620000.0
28  2026-02-11   96.17   97.63   95.66   96.65   43420.0
29  2026-02-12   95.84   97.80   91.42   92.16   71216.0
30  2026-02-13   94.96   96.20   93.50   94.82   40301.0
31  2026-02-16   98.49  101.26   96.95   99.50   85236.0
32  2026-02-17   98.67     NaN   97.19  101.93   89758.0
33  2026-02-18   96.96   98.53   95.38   96.22   92322.0
34  2026-02-19   98.64   99.32   95.75   97.32   40699.0
35  2026-01-22  103.28  106.28  102.27  105.21   84080.0
36  2026-02-23   97.22  100.49   96.23   99.35   98483.0
37  2026-02-24   93.89   95.72   92.27   94.85   40190.0
38  2026-02-25   91.70   92.28   89.47   90.94   50492.0
39  2026-02-26   92.26   95.27   90.49   93.59   90132.0
40  2026-02-27   93.79   96.14   92.30   94.28   75743.0
41  2026-03-02   94.30   97.07   92.95   96.54  850000.0
42  2026-03-03   94.29   95.81   92.55   93.19   90336.0
43  2026-03-04   93.95   94.90   92.54   93.59   92479.0
44  2026-03-05     NaN   93.27   90.10   91.00   59778.0
45  2026-03-06   90.39   91.24   86.89   87.76   97471.0
46  2026-03-09   89.76   92.53   87.80   90.65   66641.0
47  2026-02-06   98.04  100.96   97.53   99.98   72635.0
48  2026-03-11   92.68   95.36   90.84   92.99   72745.0
49  2026-03-12   89.71   90.49   88.09   89.54   95006.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    50 non-null     object
 1   Open    49 non-null     float64
 2   High    49 non-null     float64
 3   Low     50 non-null     float64
 4   Close   49 non-null     float64
 5   Volume  49 non-null     float64
dtypes: float64(5), object(1)
memory usage: 2.5+ KB

In [6]:
df.head()

         Date    Open    High     Low   Close   Volume
0  2026-01-02  101.09  103.37  100.08  102.04  89377.0
1  2026-01-05  101.05  101.99   99.91  100.58  88404.0
2  2026-01-06  102.41  103.15   99.47  101.36  94045.0
3  2026-01-07  105.35  108.05  103.53  106.87  72352.0
4  2026-01-08  105.13  109.88  104.24  107.49  79790.0

In [7]:
df["Date"]=pd.to_datetime(df["Date"])

In [8]:
df.dtypes

Date      datetime64[ns]
Open             float64
High             float64
Low              float64
Close            float64
Volume           float64
dtype: object

In [9]:
df.isnull().sum()

Date      0
Open      1
High      1
Low       0
Close     1
Volume    1
dtype: int64

In [10]:
df=df.dropna()

In [21]:
df=df.isnull().sum()

In [22]:
df.isnull().sum()

np.int64(0)

In [23]:
df.duplicated().sum()

np.int64(5)

In [34]:
df["Price_delta"] = df["Close"] - df["Open"]
df

Date            0.0
Open            0.0
High            0.0
Low             0.0
Close           0.0
Volume          0.0
Volume_MA_7     6.0
Price_delta     0.0
Daily_Return    NaN
dtype: float64

In [25]:
df["Daily_Return"]=(df["Close"]-df["Open"]/df["Open"])*100
df

C:\Users\Admin\AppData\Local\Temp\ipykernel_6536\1436092743.py:1: RuntimeWarning: invalid value encountered in scalar divide
  df["Daily_Return"]=(df["Close"]-df["Open"]/df["Open"])*100

Date            0.0
Open            0.0
High            0.0
Low             0.0
Close           0.0
Volume          0.0
Volume_MA_7     6.0
Price_delta     0.0
Daily_Return    NaN
dtype: float64

In [32]:
df["Volume"].mean()

np.float64(0.0)

In [30]:
df["Volume"].max()

np.float64(0.0)

In [33]:
#moving average of volumn
df["Volume_MA_7"] = df["Volume"].rolling(7).mean()

AttributeError: 'numpy.float64' object has no attribute 'rolling'

In [19]:
df

     Date   Open   High    Low  Close  Volume  Volume_MA_7
0   False  False  False  False  False   False          NaN
1   False  False  False  False  False   False          NaN
2   False  False  False  False  False   False          NaN
3   False  False  False  False  False   False          NaN
4   False  False  False  False  False   False          NaN
5   False  False  False  False  False   False          NaN
6   False  False  False  False  False   False          0.0
8   False  False  False  False  False   False          0.0
9   False  False  False  False  False   False          0.0
10  False  False  False  False  False   False          0.0
11  False  False  False  False  False   False          0.0
12  False  False  False  False  False   False          0.0
13  False  False  False  False  False   False          0.0
14  False  False  False  False  False   False          0.0
15  False  False  False  False  False   False          0.0
16  False  False  False  False  False   False          0.0
17  False  False  False  False  False   False          0.0
19  False  False  False  False  False   False          0.0
20  False  False  False  False  False   False          0.0
21  False  False  False  False  False   False          0.0
22  False  False  False  False  False   False          0.0
23  False  False  False  False  False   False          0.0
24  False  False  False  False  False   False          0.0
25  False  False  False  False  False   False          0.0
26  False  False  False  False  False   False          0.0
27  False  False  False  False  False   False          0.0
28  False  False  False  False  False   False          0.0
29  False  False  False  False  False   False          0.0
30  False  False  False  False  False   False          0.0
31  False  False  False  False  False   False          0.0
33  False  False  False  False  False   False          0.0
34  False  False  False  False  False   False          0.0
35  False  False  False  False  False   False          0.0
36  False  False  False  False  False   False          0.0
37  False  False  False  False  False   False          0.0
38  False  False  False  False  False   False          0.0
39  False  False  False  False  False   False          0.0
40  False  False  False  False  False   False          0.0
41  False  False  False  False  False   False          0.0
42  False  False  False  False  False   False          0.0
43  False  False  False  False  False   False          0.0
45  False  False  False  False  False   False          0.0
46  False  False  False  False  False   False          0.0
47  False  False  False  False  False   False          0.0
48  False  False  False  False  False   False          0.0
49  False  False  False  False  False   False          0.0

In [24]:
#identifying anomlies means errors
Volume_mean=df["Volume"].mean()
Volume_mean

np.float64(111812.21739130435)

In [20]:
#identifying anomlies means errors
Volume_std=df["Volume"].std()
Volume_std

148250.65636907922

In [25]:
Volume_threshold=Volume_mean+(2*Volume_std)

In [27]:
anomalies=df[df["Volume"]>Volume_threshold]
anomalies

,Date,Open,High,Low,Close,Volume,Price_delta,Daily_Return,Volume_MA_7
11,2026-01-19,108.79,109.79,106.87,108.72,450000.0,-0.07,10772.0,122103.285714
27,2026-02-10,97.05,99.07,95.25,96.75,620000.0,-0.30,9575.0,152979.285714
41,2026-03-02,94.30,97.07,92.95,96.54,850000.0,2.24,9554.0,184160.000000

In [1]:
#stock retuen distrubution
mean_return=df["Daily_Return"].mean()
print("mean_return",mean_return)
variance_return=df["Daily_return"].var()
print("variance_return",variance_return)
standerd_return=df["Daily_Return"].std()
print("standard_return",standerd_return)

NameError: name 'df' is not defined